version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: scooter_postgis_db
    environment:
      POSTGRES_USER: admn
      POSTGRES_PASSWORD: 312
      POSTGRES_DB: scooter_sharing
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: